services:
  - type: web
    name: churn-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    build:
      environment:
        PYTHON_VERSION: 3.10
